INSERT INTO vacina (NOME, CATEGORIA) VALUES ('BCG', 'Recém-Nascido');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Hepatite B (1ª dose)', 'Recém Nascido');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Hepatite B (2ª dose)', 'Recém Nascido');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Hepatite B (3ª dose)', 'Recém Nascido');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Penta/DTP (1ª Dose) ', 'Bebê');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('VIP/VOP (1ª Dose)', 'Bebê');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Pneumocócia 10V (conjugada) (1ª Dose)', 'Bebê');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Rotavírus Humano (1ª Dose)', 'Bebê');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Meningocócica C (conjugada) (1ª Dose)', 'Bebê');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Penta/DTP (2ª Dose) ', 'Bebê');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('VIP/VOP (2ª Dose)', 'Bebê');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Pneumocócia 10V (conjugada) (2ª Dose)', 'Bebê');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Rotavírus Humano (2ª Dose)', 'Bebê');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Meningocócica C (conjugada) (2ª Dose)', 'Bebê');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Penta/DTP (3ª Dose) ', 'Bebê');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('VIP/VOP (3ª Dose)', 'Bebê');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Febre Amarela', 'Bebê');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Pneumocócia 10V (conjugada) (Reforço)', 'Bebê');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Meningocócica C (conjugada) (Reforço)', 'Bebê');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Tríplice Viral', 'Bebê');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Penta/DTP (1ª reforço) ', 'Bebê');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('VIP/VOP (1ª reforço)', 'Bebê');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Hepatite A', 'Bebê');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Tetra Viral', 'Bebê');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Penta/DTP (2ª reforço)', 'Criança');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('VIP/VOP (2ª reforço)', 'Criança');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Varicela', 'Criança');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Pneumocócia 23V (conjugada)', 'Criança');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Hepatite B (1ª dose)', 'Adolescente');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Hepatite B (2ª dose)', 'Adolescente');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Hepatite B (3ª dose)', 'Adolescente');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Meningocócica C', 'Adolescente');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Febre Amarela', 'Adolescente');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Tríplice viral', 'Adolescente');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('HPV', 'Adolescente');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Dupla adulto (1ª dose)', 'Adolescente');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Dupla adulto (2ª dose)', 'Adolescente');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Dupla adulto (3ª dose)', 'Adolescente');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Dupla adulto', 'Adolescente');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Hepatite B (1ª dose)', 'Adulto');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Hepatite B (2ª dose)', 'Adulto');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Hepatite B (3ª dose)', 'Adulto');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Febre Amarela', 'Adulto');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Tríplice viral', 'Adulto');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Dupla adulto', 'Adulto');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Hepatite B (1ª dose)', 'Idoso');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Hepatite B (2ª dose)', 'Idoso');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Hepatite B (3ª dose)', 'Idoso');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Febre Amarela', 'Idoso');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Dupla adulto', 'Idoso');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Influenza', 'Idoso');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Pneumocócia 23V (conjugada)', 'Idoso');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Hepatite B (1ª dose)', 'Gestante');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Hepatite B (2ª dose)', 'Gestante');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Hepatite B (3ª dose)', 'Gestante');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('Influenza', 'Gestante');
INSERT INTO vacina (NOME, CATEGORIA) VALUES ('dTpa', 'Gestante');
COMMIT;